In [38]:
#Import Library
import pandas as pd
import numpy as np
import re
import csv
import plotly.express as px

In [39]:
#Read the file saved from web scrapping
toulouse_data = pd.read_csv("./data_hotel_booking.csv",encoding = "ISO-8859-1")

In [40]:
toulouse_data.head()

,Date,ID,Hotel_Name,Stars,Reviews_score,Reviews_classification,Number_reviews,Price,Features,Night,Bed_configuration,Location,Location_Score,Lat_Long,Taxe,Web_page
0,1,51949,Campanile Toulouse Purpan,3,8.4,Very good,"2,951 reviews", 69,1 Double Bed & 1 Junior Bed - Room Next Genera...,"1 night, 1 adult","2 beds (1 single, 1 double)","Toulouse West, Toulouse Show on map 3.8 km fro...",0.0,"1.39372944831848,43.6068100365509",includes taxes and charges,https://www.booking.com/hotel/fr/campanilepurp...
1,1,22819,Le Grand Balcon Hotel,4,8.9,Fabulous,"1,084 reviews", 125,Classic Double Room  \nSleeps: 1 - 2 guests,"1 night, 1 adult",Beds: 1 double or 2 singles,"Toulouse City-Centre, Toulouse Show on map 200...",9.8,"1.44249469041824,43.6048736714363",includes taxes and charges,https://www.booking.com/hotel/fr/le-grand-balc...
2,1,55284,Best Western Hotel Innes Toulouse Centre,4,8.4,Very good,869 reviews, 87,Classic Double Room  \nSleeps: 1 - 2 guests,"1 night, 1 adult",1 double bed,"Toulouse City-Centre, Toulouse Show on map 900...",0.0,"1.44708797335625,43.6106087823946",includes taxes and charges,https://www.booking.com/hotel/fr/best-western-...
3,1,809743,Residhotel Toulouse Centre,3,8.1,Very good,"1,183 reviews", 69,Studio  \nSleeps: 1 - 2 guests,"1 night, 1 adult",1 large double bed,"Toulouse City-Centre, Toulouse Show on map 1 k...",0.0,"1.44120499480778,43.5953916105848",includes taxes and charges,https://www.booking.com/hotel/fr/residhotel-to...
4,1,57388,Pullman Toulouse Centre Ramblas,5,8.6,Fabulous,758 reviews, 165,Superior Twin Room  \nSleeps: 1 - 2 guests,"1 night, 1 adult",2 single beds,"Toulouse City-Centre, Toulouse Show on map 1.1...",0.0,"1.45334422588348,43.6085424187075",includes taxes and charges,https://www.booking.com/hotel/fr/toulouse-cent...

In [44]:
toulouse_data.tail()

,Date,ID,Hotel_Name,Stars,Reviews_score,Reviews_classification,Number_reviews,Price,Features,Night,Bed_configuration,Location,Location_Score,Lat_Long,Taxe,Web_page
6210,30,6716504,Cocoon'Inn Emeraude,0,NaN,Good,"1,437 reviews", 75,Studio  \nSleeps: 1 - 2 guests,"1 night, 1 adult",1 double bed,"Toulouse West, Toulouse Show on map 6 km from ...",0.0,"1.35816335678101,43.6059632486431",includes taxes and charges,https://www.booking.com/hotel/fr/aparthotel-ad...
6211,30,6560559,Les Minimes,0,NaN,Good,"1,437 reviews", 75,Studio  \nSleeps: 1 - 2 guests,"1 night, 1 adult",1 double bed,"Toulouse West, Toulouse Show on map 6 km from ...",0.0,"1.35816335678101,43.6059632486431",includes taxes and charges,https://www.booking.com/hotel/fr/aparthotel-ad...
6212,30,5802745,Appartement Capitole Toulouse,0,NaN,Good,"1,437 reviews", 75,Studio  \nSleeps: 1 - 2 guests,"1 night, 1 adult",1 double bed,"Toulouse West, Toulouse Show on map 6 km from ...",0.0,"1.35816335678101,43.6059632486431",includes taxes and charges,https://www.booking.com/hotel/fr/aparthotel-ad...
6213,30,825451,Coquet Studio Fonctionnel,0,9.0,Superb,8 reviews, 84,Studio (2 Adults)  \nSleeps: 1 - 2 guests,"1 night, 1 adult",1 double bed,"Toulouse West, Toulouse Show on map 3.9 km fro...",9.4,"1.39565125107765,43.6144538179667",includes taxes and charges,https://www.booking.com/hotel/fr/beau-studio-f...
6214,30,6894791,"Central & Calme, Design & Zen, Netflix gratuit",0,NaN,Superb,8 reviews, 84,Studio (2 Adults)  \nSleeps: 1 - 2 guests,"1 night, 1 adult",1 double bed,"Toulouse West, Toulouse Show on map 3.9 km fro...",9.4,"1.39565125107765,43.6144538179667",includes taxes and charges,https://www.booking.com/hotel/fr/beau-studio-f...

In [45]:
toulouse_data.shape

(6215, 16)

In [41]:
toulouse_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6215 entries, 0 to 6214
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Date                    6215 non-null   int64
 1   ID                      6215 non-null   int64
 2   Hotel_Name              6215 non-null   object
 3   Stars                   6215 non-null   int64
 4   Reviews_score           5454 non-null   float64
 5   Reviews_classification  6215 non-null   object
 6   Number_reviews          6215 non-null   object
 7   Price                   6215 non-null   object
 8   Features                6215 non-null   object
 9   Night                   6215 non-null   object
 10  Bed_configuration       6215 non-null   object
 11  Location                6215 non-null   object
 12  Location_Score          6215 non-null   float64
 13  Lat_Long                6215 non-null   object
 14  Taxe                    6215 non-null   object
 15  Web_page                6215 non-null   object
dtypes: float64(2), int64(3), object(11)
memory usage: 777.0+ KB

In [42]:
toulouse_data.columns

Index(['Date', 'ID', 'Hotel_Name', 'Stars', 'Reviews_score',
       'Reviews_classification', 'Number_reviews', 'Price', 'Features',
       'Night', 'Bed_configuration', 'Location', 'Location_Score', 'Lat_Long',
       'Taxe', 'Web_page'],
      dtype='object')

In [46]:
#Number of missing /no value data in dataframe
toulouse_data.isna().sum().sum()

761

In [47]:
 toulouse_data.isnull().sum()

Date                        0
ID                          0
Hotel_Name                  0
Stars                       0
Reviews_score             761
Reviews_classification      0
Number_reviews              0
Price                       0
Features                    0
Night                       0
Bed_configuration           0
Location                    0
Location_Score              0
Lat_Long                    0
Taxe                        0
Web_page                    0
dtype: int64

In [43]:
toulouse_data.isna().sum()

Date                        0
ID                          0
Hotel_Name                  0
Stars                       0
Reviews_score             761
Reviews_classification      0
Number_reviews              0
Price                       0
Features                    0
Night                       0
Bed_configuration           0
Location                    0
Location_Score              0
Lat_Long                    0
Taxe                        0
Web_page                    0
dtype: int64

In [48]:
#split the distance from location
toulouse_data[['Location','Distance']] = toulouse_data.Location.apply(lambda x: pd.Series(str(x).split(", Toulouse Show on map")))

In [49]:
#create news columns for metro access
toulouse_data[['Distance', 'Metro_access']] = toulouse_data.Distance.apply(lambda x: pd.Series(str(x).split("from centre")))

In [50]:
toulouse_data[['Features', 'Occupancy']] = toulouse_data.Features.apply(lambda x: pd.Series(str(x).split("Sleeps:")))

In [51]:
toulouse_data[['Number_reviews']] = toulouse_data.Number_reviews.apply(lambda x: pd.Series(str(x).replace("reviews","")))
toulouse_data[['Number_reviews']] = toulouse_data.Number_reviews.apply(lambda x: pd.Series(str(x).replace(",","")))

In [52]:
toulouse_data[['Features']] = toulouse_data.Features.apply(lambda x: pd.Series(str(x).replace("\n","")))
toulouse_data[['Features']] = toulouse_data.Features.apply(lambda x: pd.Series(str(x).replace(" – ","")))

In [53]:
toulouse_data[['Distance','Measurement']] = toulouse_data.Distance.apply(lambda x: pd.Series(str(x).split()))

In [54]:
toulouse_data[['Longitude','Latitude']] = toulouse_data.Lat_Long.apply(lambda x: pd.Series(str(x).split(",")))

In [55]:
toulouse_data.head()

,Date,ID,Hotel_Name,Stars,Reviews_score,Reviews_classification,Number_reviews,Price,Features,Night,...,Location_Score,Lat_Long,Taxe,Web_page,Distance,Metro_access,Occupancy,Measurement,Longitude,Latitude
0,1,51949,Campanile Toulouse Purpan,3,8.4,Very good,2951, 69,1 Double Bed & 1 Junior Bed - Room Next Genera...,"1 night, 1 adult",...,0.0,"1.39372944831848,43.6068100365509",includes taxes and charges,https://www.booking.com/hotel/fr/campanilepurp...,3.8,,1 - 2 guests,km,1.39372944831848,43.6068100365509
1,1,22819,Le Grand Balcon Hotel,4,8.9,Fabulous,1084, 125,Classic Double Room ,"1 night, 1 adult",...,9.8,"1.44249469041824,43.6048736714363",includes taxes and charges,https://www.booking.com/hotel/fr/le-grand-balc...,200,Metro access,1 - 2 guests,m,1.44249469041824,43.6048736714363
2,1,55284,Best Western Hotel Innes Toulouse Centre,4,8.4,Very good,869, 87,Classic Double Room ,"1 night, 1 adult",...,0.0,"1.44708797335625,43.6106087823946",includes taxes and charges,https://www.booking.com/hotel/fr/best-western-...,900,Metro access,1 - 2 guests,m,1.44708797335625,43.6106087823946
3,1,809743,Residhotel Toulouse Centre,3,8.1,Very good,1183, 69,Studio ,"1 night, 1 adult",...,0.0,"1.44120499480778,43.5953916105848",includes taxes and charges,https://www.booking.com/hotel/fr/residhotel-to...,1,Metro access,1 - 2 guests,km,1.44120499480778,43.5953916105848
4,1,57388,Pullman Toulouse Centre Ramblas,5,8.6,Fabulous,758, 165,Superior Twin Room ,"1 night, 1 adult",...,0.0,"1.45334422588348,43.6085424187075",includes taxes and charges,https://www.booking.com/hotel/fr/toulouse-cent...,1.1,Metro access,1 - 2 guests,km,1.45334422588348,43.6085424187075

In [56]:
toulouse_data.Latitude = toulouse_data.Latitude.astype(float)

In [57]:
toulouse_data.Longitude = toulouse_data.Longitude.astype(float)

In [58]:
toulouse_data.Distance = toulouse_data.Distance.astype(float)

In [59]:
#cleaning price, remove euros sign
def remove_euros_signs(price):
    price_val = re.findall('[0-9]',price)
    return "".join(price_val)

toulouse_data.Price = toulouse_data.Price.apply(remove_euros_signs)

In [60]:
toulouse_data.Price = toulouse_data.Price.astype(int)

In [61]:
#convert the distance into km using a for loop
for i in range(len(toulouse_data)):
    if toulouse_data.loc[i, "Measurement"] == "m":
        toulouse_data.loc[i, "Distance_km"] = toulouse_data.loc[i, "Distance"]/1000
    else:
        toulouse_data.loc[i, "Distance_km"] = toulouse_data.loc[i, "Distance"]

In [62]:
##Add difference categories for distance
for i in range(len(toulouse_data)):
    if toulouse_data.loc[i, "Distance_km"] <= 2:
        toulouse_data.loc[i, "Distance_classification"] = '2_km'
        
    elif toulouse_data.loc[i, "Distance_km"] <= 4:
        toulouse_data.loc[i, "Distance_classification"] = '4_km'
        
    elif toulouse_data.loc[i, "Distance_km"] <= 6:
        toulouse_data.loc[i, "Distance_classification"] = '6_km'
        
    elif toulouse_data.loc[i, "Distance_km"] <= 8:
        toulouse_data.loc[i, "Distance_classification"] = '8_km'
    else:
        toulouse_data.loc[i, "Distance_classification"] = 'Far'

In [63]:
toulouse_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6215 entries, 0 to 6214
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Date                     6215 non-null   int64
 1   ID                       6215 non-null   int64
 2   Hotel_Name               6215 non-null   object
 3   Stars                    6215 non-null   int64
 4   Reviews_score            5454 non-null   float64
 5   Reviews_classification   6215 non-null   object
 6   Number_reviews           6215 non-null   object
 7   Price                    6215 non-null   int32
 8   Features                 6215 non-null   object
 9   Night                    6215 non-null   object
 10  Bed_configuration        6215 non-null   object
 11  Location                 6215 non-null   object
 12  Location_Score           6215 non-null   float64
 13  Lat_Long                 6215 non-null   object
 14  Taxe                     6215 non-null   object
 15  Web_page                 6215 non-null   object
 16  Distance                 6152 non-null   float64
 17  Metro_access             6152 non-null   object
 18  Occupancy                6122 non-null   object
 19  Measurement              6152 non-null   object
 20  Longitude                6215 non-null   float64
 21  Latitude                 6215 non-null   float64
 22  Distance_km              6152 non-null   float64
 23  Distance_classification  6215 non-null   object
dtypes: float64(6), int32(1), int64(3), object(14)
memory usage: 1.1+ MB

In [64]:
#remove colums unnecessary colums from data frame
del toulouse_data['Distance']
del toulouse_data['Measurement']
del toulouse_data['Lat_Long']

In [65]:
toulouse_data.head()

,Date,ID,Hotel_Name,Stars,Reviews_score,Reviews_classification,Number_reviews,Price,Features,Night,...,Location,Location_Score,Taxe,Web_page,Metro_access,Occupancy,Longitude,Latitude,Distance_km,Distance_classification
0,1,51949,Campanile Toulouse Purpan,3,8.4,Very good,2951,69,1 Double Bed & 1 Junior Bed - Room Next Genera...,"1 night, 1 adult",...,Toulouse West,0.0,includes taxes and charges,https://www.booking.com/hotel/fr/campanilepurp...,,1 - 2 guests,1.393729,43.606810,3.8,4_km
1,1,22819,Le Grand Balcon Hotel,4,8.9,Fabulous,1084,125,Classic Double Room ,"1 night, 1 adult",...,Toulouse City-Centre,9.8,includes taxes and charges,https://www.booking.com/hotel/fr/le-grand-balc...,Metro access,1 - 2 guests,1.442495,43.604874,0.2,2_km
2,1,55284,Best Western Hotel Innes Toulouse Centre,4,8.4,Very good,869,87,Classic Double Room ,"1 night, 1 adult",...,Toulouse City-Centre,0.0,includes taxes and charges,https://www.booking.com/hotel/fr/best-western-...,Metro access,1 - 2 guests,1.447088,43.610609,0.9,2_km
3,1,809743,Residhotel Toulouse Centre,3,8.1,Very good,1183,69,Studio ,"1 night, 1 adult",...,Toulouse City-Centre,0.0,includes taxes and charges,https://www.booking.com/hotel/fr/residhotel-to...,Metro access,1 - 2 guests,1.441205,43.595392,1.0,2_km
4,1,57388,Pullman Toulouse Centre Ramblas,5,8.6,Fabulous,758,165,Superior Twin Room ,"1 night, 1 adult",...,Toulouse City-Centre,0.0,includes taxes and charges,https://www.booking.com/hotel/fr/toulouse-cent...,Metro access,1 - 2 guests,1.453344,43.608542,1.1,2_km

In [66]:
 toulouse_data.isnull().sum()

Date                         0
ID                           0
Hotel_Name                   0
Stars                        0
Reviews_score              761
Reviews_classification       0
Number_reviews               0
Price                        0
Features                     0
Night                        0
Bed_configuration            0
Location                     0
Location_Score               0
Taxe                         0
Web_page                     0
Metro_access                63
Occupancy                   93
Longitude                    0
Latitude                     0
Distance_km                 63
Distance_classification      0
dtype: int64

In [67]:
toulouse_data.isna().sum()

Date                         0
ID                           0
Hotel_Name                   0
Stars                        0
Reviews_score              761
Reviews_classification       0
Number_reviews               0
Price                        0
Features                     0
Night                        0
Bed_configuration            0
Location                     0
Location_Score               0
Taxe                         0
Web_page                     0
Metro_access                63
Occupancy                   93
Longitude                    0
Latitude                     0
Distance_km                 63
Distance_classification      0
dtype: int64

In [68]:
#Rearrange the coulmns
toulouse_clean_df = toulouse_data[['Date', 'ID', 'Hotel_Name' , 'Price', 'Stars', 'Reviews_score', 'Reviews_classification','Number_reviews', 'Location', 'Distance_km', 'Location_Score', 'Longitude', 'Latitude', 'Metro_access','Features', 'Bed_configuration', 'Night', 'Occupancy','Taxe', 'Web_page']]

In [69]:
toulouse_clean_df.head()

,Date,ID,Hotel_Name,Price,Stars,Reviews_score,Reviews_classification,Number_reviews,Location,Distance_km,Location_Score,Longitude,Latitude,Metro_access,Features,Bed_configuration,Night,Occupancy,Taxe,Web_page
0,1,51949,Campanile Toulouse Purpan,69,3,8.4,Very good,2951,Toulouse West,3.8,0.0,1.393729,43.606810,,1 Double Bed & 1 Junior Bed - Room Next Genera...,"2 beds (1 single, 1 double)","1 night, 1 adult",1 - 2 guests,includes taxes and charges,https://www.booking.com/hotel/fr/campanilepurp...
1,1,22819,Le Grand Balcon Hotel,125,4,8.9,Fabulous,1084,Toulouse City-Centre,0.2,9.8,1.442495,43.604874,Metro access,Classic Double Room ,Beds: 1 double or 2 singles,"1 night, 1 adult",1 - 2 guests,includes taxes and charges,https://www.booking.com/hotel/fr/le-grand-balc...
2,1,55284,Best Western Hotel Innes Toulouse Centre,87,4,8.4,Very good,869,Toulouse City-Centre,0.9,0.0,1.447088,43.610609,Metro access,Classic Double Room ,1 double bed,"1 night, 1 adult",1 - 2 guests,includes taxes and charges,https://www.booking.com/hotel/fr/best-western-...
3,1,809743,Residhotel Toulouse Centre,69,3,8.1,Very good,1183,Toulouse City-Centre,1.0,0.0,1.441205,43.595392,Metro access,Studio ,1 large double bed,"1 night, 1 adult",1 - 2 guests,includes taxes and charges,https://www.booking.com/hotel/fr/residhotel-to...
4,1,57388,Pullman Toulouse Centre Ramblas,165,5,8.6,Fabulous,758,Toulouse City-Centre,1.1,0.0,1.453344,43.608542,Metro access,Superior Twin Room ,2 single beds,"1 night, 1 adult",1 - 2 guests,includes taxes and charges,https://www.booking.com/hotel/fr/toulouse-cent...

In [70]:
toulouse_clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6215 entries, 0 to 6214
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Date                    6215 non-null   int64
 1   ID                      6215 non-null   int64
 2   Hotel_Name              6215 non-null   object
 3   Price                   6215 non-null   int32
 4   Stars                   6215 non-null   int64
 5   Reviews_score           5454 non-null   float64
 6   Reviews_classification  6215 non-null   object
 7   Number_reviews          6215 non-null   object
 8   Location                6215 non-null   object
 9   Distance_km             6152 non-null   float64
 10  Location_Score          6215 non-null   float64
 11  Longitude               6215 non-null   float64
 12  Latitude                6215 non-null   float64
 13  Metro_access            6152 non-null   object
 14  Features                6215 non-null   object
 15  Bed_configuration       6215 non-null   object
 16  Night                   6215 non-null   object
 17  Occupancy               6122 non-null   object
 18  Taxe                    6215 non-null   object
 19  Web_page                6215 non-null   object
dtypes: float64(5), int32(1), int64(3), object(11)
memory usage: 946.9+ KB

In [71]:
#write cleanned data to a new csv file

toulouse_clean_df.to_csv('toulouse_data_clean.csv', encoding = "ISO-8859-1")